import { Component, OnInit } from '@angular/core';
import { MemberProfileService, BODY_TYPES, TRAINING_GOALS, ACTIVITY_LEVELS, Client } from '@shared';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-profile',
  template: `<div class="page-container profile-page"><header class="page-header"><h1>Mi perfil</h1><p>Mantén actualizados tus datos para que FitMentor personalice tus rutinas.</p></header><section class="card"><form (ngSubmit)="save()" #form="ngForm"><h2>Datos personales</h2><div class="grid"><label>Nombre completo<input class="app-input" [(ngModel)]="profile.name" name="name" required></label><label>Correo electrónico<input class="app-input" type="email" [(ngModel)]="profile.email" name="email"></label><label>Teléfono<input class="app-input" [(ngModel)]="profile.phone" name="phone"></label><label>Fecha de nacimiento<input class="app-input" type="date" [(ngModel)]="profile.birth_date" name="birth_date"></label><label>Sexo<select class="app-input" [(ngModel)]="profile.sex" name="sex"><option [ngValue]="null">No especificado</option><option value="masculino">Masculino</option><option value="femenino">Femenino</option><option value="otro">Otro</option></select></label><label>Contacto de emergencia<input class="app-input" [(ngModel)]="profile.emergency_contact" name="emergency_contact"></label></div><h2>Perfil físico y objetivo</h2><div class="grid"><label>Altura (cm)<input class="app-input" type="number" min="80" max="250" [(ngModel)]="profile.height_cm" name="height_cm"></label><label>Tipo de cuerpo<select class="app-input" [(ngModel)]="profile.body_type" name="body_type"><option [ngValue]="null">No estoy seguro</option><option *ngFor="let type of bodyTypes" [value]="type.value">{{type.label}}</option></select><small *ngIf="selectedBody">{{selectedBody.description}}</small></label><label>Objetivo<select class="app-input" [(ngModel)]="profile.goal" name="goal"><option [ngValue]="null">Selecciona un objetivo</option><option *ngFor="let goal of goals" [value]="goal.value">{{goal.label}}</option></select></label><label>Actividad diaria<select class="app-input" [(ngModel)]="profile.daily_activity" name="daily_activity"><option [ngValue]="null">Selecciona tu actividad</option><option *ngFor="let level of activityLevels" [value]="level.value">{{level.label}}</option></select></label><label class="full">Lesiones o molestias<textarea class="app-input" rows="3" [(ngModel)]="profile.injuries" name="injuries"></textarea></label><label class="full">Restricciones<textarea class="app-input" rows="3" [(ngModel)]="profile.restrictions" name="restrictions"></textarea></label></div><button class="btn btn-primary btn-block" type="submit" [disabled]="saving || form.invalid">{{saving ? 'Guardando...' : 'Guardar perfil'}}</button></form></section></div>`,
  styles: [`.profile-page{max-width:760px}.card{padding:1.5rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem 1.25rem}h2{font-size:1.1rem;margin:0 0 1rem}h2:not(:first-child){margin-top:1.75rem;padding-top:1.25rem;border-top:1px solid var(--app-border)}label{display:flex;flex-direction:column;gap:.4rem;font-weight:600;color:var(--text-muted);font-size:.85rem}.app-input{margin:0}small{font-weight:400;line-height:1.35}.full{grid-column:1/-1}.btn-block{margin-top:1.1rem}@media(max-width:600px){.page-container{padding:.75rem 0}.card{padding:1rem}.grid{grid-template-columns:1fr;gap:.85rem}.full{grid-column:auto}.btn-block{margin-top:1.25rem}}`]
})
export class ProfileComponent implements OnInit {
  profile: Partial<Client> = { name: '' };
  bodyTypes = BODY_TYPES; goals = TRAINING_GOALS; activityLevels = ACTIVITY_LEVELS; saving = false;
  constructor(private service: MemberProfileService) {}
  get selectedBody() { return this.bodyTypes.find(t => t.value === this.profile.body_type); }
  ngOnInit(): void { this.service.get().subscribe({ next: p => this.profile = { ...p, birth_date: p.birth_date ? p.birth_date.slice(0, 10) : null, body_type: this.normalizeBodyType(p.body_type) }, error: () => void Swal.fire('Error', 'No se pudo cargar tu perfil.', 'error') }); }
  private normalizeBodyType(value: string | null | undefined): string | null { const v = (value || '').trim().toLowerCase(); return ({ ectomorfo: 'ectomorph', mesomorfo: 'mesomorph', endomorfo: 'endomorph' } as Record<string, string>)[v] || (v || null); }
  save(): void { this.saving = true; this.service.update(this.profile).subscribe({ next: p => { this.profile = p; this.saving = false; void Swal.fire('Perfil actualizado', 'Tus datos se guardaron correctamente.', 'success'); }, error: err => { this.saving = false; void Swal.fire('No se pudo guardar', err?.error?.detail || 'Revisa los datos e inténtalo nuevamente.', 'error'); } }); }
}
