import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '@shared';

@Component({
  selector: 'app-activate-account',
  template: `<div class="auth-page"><div class="auth-card"><h1>Activa tu cuenta</h1><p>Usa al menos 6 caracteres y evita contraseñas comunes.</p><form (ngSubmit)="submit()"><div class="password-field"><input class="app-input" [type]="showPassword ? 'text' : 'password'" [(ngModel)]="password" name="password" minlength="6" placeholder="Nueva contraseña" required><button type="button" class="password-toggle" (click)="showPassword = !showPassword" [attr.aria-label]="showPassword ? 'Ocultar contraseña' : 'Mostrar contraseña'"><svg viewBox="0 0 24 24" aria-hidden="true"><path *ngIf="!showPassword" d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle *ngIf="!showPassword" cx="12" cy="12" r="2.5"/><path *ngIf="showPassword" d="m3 3 18 18M10.6 6.2A10.8 10.8 0 0 1 12 6c6.5 0 10 6 10 6a17.7 17.7 0 0 1-3.2 3.7M6.2 6.2C3.6 7.8 2 12 2 12s3.5 6 10 6c1.8 0 3.3-.4 4.6-1.1"/></svg></button></div><div class="password-field"><input class="app-input" [type]="showConfirmation ? 'text' : 'password'" [(ngModel)]="confirmation" name="confirmation" minlength="6" placeholder="Repite tu contraseña" required><button type="button" class="password-toggle" (click)="showConfirmation = !showConfirmation" [attr.aria-label]="showConfirmation ? 'Ocultar confirmación' : 'Mostrar confirmación'"><svg viewBox="0 0 24 24" aria-hidden="true"><path *ngIf="!showConfirmation" d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle *ngIf="!showConfirmation" cx="12" cy="12" r="2.5"/><path *ngIf="showConfirmation" d="m3 3 18 18M10.6 6.2A10.8 10.8 0 0 1 12 6c6.5 0 10 6 10 6a17.7 17.7 0 0 1-3.2 3.7M6.2 6.2C3.6 7.8 2 12 2 12s3.5 6 10 6c1.8 0 3.3-.4 4.6-1.1"/></svg></button></div><button class="btn btn-primary btn-block" [disabled]="loading">{{loading ? 'Guardando...' : 'Guardar contraseña'}}</button><p class="alert alert-danger" *ngIf="error">{{error}}</p><p class="alert alert-success" *ngIf="success">{{success}}</p></form></div></div>`,
  styles: [`.auth-page{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:1rem;background:var(--app-bg)}.auth-card{width:100%;max-width:400px;padding:2rem;background:var(--app-surface);border:1px solid var(--app-border);border-radius:var(--radius-xl);color:var(--text-main)}.password-field{position:relative}.app-input{width:100%;margin:1rem 0;padding:.75rem;padding-right:3rem;color:var(--text-main);border:1px solid var(--app-border-strong);border-radius:8px;background:var(--app-surface);font:inherit}.password-toggle{position:absolute;right:8px;top:50%;transform:translateY(-50%);border:0;background:transparent;color:var(--lime-700);cursor:pointer;padding:5px;display:grid;place-items:center}.password-toggle svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.btn-block{width:100%}`]
})
export class ActivateAccountComponent {
  password = ''; confirmation = ''; showPassword = false; showConfirmation = false; loading = false; error = ''; success = '';
  token = this.route.snapshot.queryParamMap.get('token') || '';
  reset = this.route.snapshot.queryParamMap.get('reset') || '';
  constructor(private route: ActivatedRoute, private http: HttpClient, private router: Router) {}
  submit() { if (this.password.length < 6) { this.error = 'La contraseña debe tener al menos 6 caracteres'; return; } if (this.password !== this.confirmation) { this.error = 'Las contraseñas no coinciden'; return; } this.loading = true; this.error = ''; const payload = { reset: this.reset, password: this.password }; this.http.post(`${environment.apiUrl}/auth/member/set-password`, payload).subscribe({ next: () => { this.success = 'Contraseña configurada. Ya puedes iniciar sesión.'; this.loading = false; setTimeout(() => this.router.navigate(['/login']), 1800); }, error: e => { this.error = e.error?.detail || 'No se pudo activar la cuenta'; this.loading = false; } }); }
}
