import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '@shared';

@Component({
  selector: 'app-forgot-password',
  template: `<div class="auth-page"><div class="auth-card"><div class="auth-brand"><img src="assets/icons/icon-member-192.png" alt="MyGym" class="auth-logo-image"><h1>Restablecer contraseña</h1><p>Portal del Socio</p></div><form (ngSubmit)="submit()"><label class="field">Correo o teléfono<input type="text" class="app-input" [(ngModel)]="identifier" name="identifier" placeholder="correo@ejemplo.com o teléfono" required autocomplete="username"></label><button class="btn btn-primary btn-block" [disabled]="loading">{{loading ? 'Enviando...' : 'Enviar enlace'}}</button><p class="auth-hint">Recibirás el enlace por correo o WhatsApp, según tus datos.</p><p class="alert alert-success" *ngIf="message">{{message}}</p><p class="alert alert-danger" *ngIf="error">{{error}}</p><button type="button" class="back-link" (click)="router.navigate(['/login'])">Volver al inicio de sesión</button></form></div></div>`,
  styles: [`.auth-page{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:1rem;background:radial-gradient(60rem 40rem at 110% -10%,var(--lime-100) 0%,transparent 55%),var(--app-bg)}.auth-card{width:100%;max-width:400px;padding:2rem;background:var(--app-surface);border:1px solid var(--app-border);border-radius:var(--radius-xl);box-shadow:var(--shadow-lg);color:var(--text-main)}.auth-brand{text-align:center;margin-bottom:1.5rem}.auth-logo-image{width:52px;height:52px;object-fit:cover;border-radius:14px}.auth-brand h1{font-size:1.5rem;margin:1rem 0 .35rem}.auth-brand p,.intro{color:var(--text-muted)}.intro{font-size:.9rem;line-height:1.5}.field{display:block;margin:1.25rem 0;font-weight:600}.app-input{display:block;width:100%;margin-top:.45rem;padding:.75rem;color:var(--text-main);border:1px solid var(--app-border-strong);border-radius:8px;background:var(--app-surface);font:inherit}.app-input:focus{outline:0;border-color:var(--app-primary);box-shadow:var(--shadow-focus)}.btn-block{width:100%}.back-link{display:block;margin:1rem auto 0;border:0;background:none;color:var(--text-muted);cursor:pointer;font:inherit;font-size:.85rem}.back-link:hover{color:var(--lime-700)}`]
})
export class ForgotPasswordComponent {
  identifier = ''; loading = false; message = ''; error = '';
  constructor(private authService: AuthService, public router: Router) {}
  submit(): void { if (!this.identifier.trim()) return; this.loading = true; this.message = ''; this.error = ''; this.authService.forgotPassword(this.identifier.trim()).subscribe({ next: result => { this.message = result.message; this.loading = false; }, error: () => { this.message = 'Si los datos corresponden a una cuenta activa, recibirás un enlace por correo electrónico.'; this.loading = false; } }); }
}
