import { Component, OnInit } from '@angular/core';
import { Tenant, TenantService, WahaStatus } from '@shared';

@Component({
  selector: 'app-platform-waha-settings',
  template: `
    <section class="waha-page">
      <div class="page-heading"><div><span class="eyebrow">Integraciones</span><h1>WhatsApp / WAHA</h1><p>Administra la sesión master del SaaS y la sesión que usará cada tenant.</p></div></div>
      <div class="cards">
        <article class="card master-card"><div class="card-title"><div><span class="eyebrow">SaaS</span><h2>Sesión master</h2></div><span class="badge" [class.ok]="status?.active" [class.warn]="!status?.active">{{ status?.active ? 'Configurada' : 'No configurada' }}</span></div><p>Se usa para recuperación de contraseña y mensajes propios de la plataforma.</p><div class="details" *ngIf="status?.active"><span>Sesión</span><strong>{{ status?.session }}</strong><span>Servidor</span><strong>{{ status?.base_url }}</strong></div><p class="muted" *ngIf="!loading && !status?.active">Define WAHA_BASE_URL y WAHA_SYSTEM_INSTANCE en el entorno del backend.</p><div class="test-box"><h3>Enviar mensaje de prueba</h3><label>Teléfono mexicano<input class="app-input" [(ngModel)]="testPhone" inputmode="numeric" maxlength="10" placeholder="5512345678"></label><small>Solo los 10 dígitos; se agregará +52 automáticamente.</small><label>Mensaje<textarea class="app-input" [(ngModel)]="testMessage" maxlength="500" rows="3" placeholder="Mensaje de prueba desde MyGym"></textarea></label><button class="btn btn-primary" [disabled]="testing || !status?.active" (click)="sendTest()">{{ testing ? 'Enviando...' : 'Enviar prueba' }}</button><p class="message" [class.error]="testError" *ngIf="testResult">{{ testResult }}</p></div></article>
        <article class="card"><div class="card-title"><div><span class="eyebrow">Tenants</span><h2>Sesión por gimnasio</h2></div></div><label>Tenant<select class="app-input" [(ngModel)]="selectedId" (ngModelChange)="selectTenant()"><option [ngValue]="null">Selecciona un tenant</option><option *ngFor="let tenant of tenants" [ngValue]="tenant.id">{{ tenant.name }}</option></select></label><div *ngIf="selectedTenant"><label>Nombre de sesión WAHA<input class="app-input" [(ngModel)]="selectedTenant.waha_session" placeholder="session_gimnasio_01"></label><label class="check"><input type="checkbox" [(ngModel)]="selectedTenant.waha_enabled"> Sesión habilitada</label><button class="btn btn-primary" [disabled]="saving" (click)="save()">{{ saving ? 'Guardando...' : 'Guardar configuración' }}</button><p class="message" [class.error]="messageError" *ngIf="message">{{ message }}</p></div><p class="muted" *ngIf="!selectedTenant">Selecciona un tenant para configurar su sesión.</p></article>
      </div>
      <div class="card tenants-card"><h2>Estado por tenant</h2><div class="tenant-row" *ngFor="let tenant of tenants"><div><strong>{{ tenant.name }}</strong><small>{{ tenant.waha_session || 'Sin sesión asignada' }}</small></div><span class="badge" [class.ok]="tenant.waha_enabled && tenant.waha_session" [class.warn]="!tenant.waha_enabled || !tenant.waha_session">{{ tenant.waha_enabled && tenant.waha_session ? 'Activo' : 'Pendiente' }}</span></div></div>
    </section>`,
  styles: [`:host{display:block;color:var(--text-main)}.waha-page{max-width:1100px;margin:0 auto}.page-heading{margin-bottom:1.5rem}.page-heading h1{color:var(--text-main)}.page-heading p{color:var(--text-muted)}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.card{background:var(--app-surface);color:var(--text-main);border:1px solid var(--app-border);border-radius:var(--radius-lg);padding:1.5rem;box-shadow:var(--shadow-sm)}.card-title{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.card h2{margin:.25rem 0 1rem;color:var(--text-main)}.card h3{margin:1.5rem 0 .5rem;color:var(--text-main)}.card p{color:var(--text-muted);line-height:1.55}.eyebrow{color:var(--lime-700)}.badge{padding:.35rem .7rem;border-radius:999px;background:var(--warning-bg);color:#92400e;font-size:.78rem;font-weight:700}.badge.ok{background:var(--success-bg);color:#166534}.badge.warn{background:var(--warning-bg);color:#92400e}.details{display:grid;grid-template-columns:110px 1fr;gap:.7rem;font-size:.9rem}.details span,.muted,small{color:var(--text-muted)}.details strong{color:var(--text-main);overflow-wrap:anywhere}.test-box{margin-top:1.25rem;padding-top:1rem;border-top:1px solid var(--app-border)}label{display:block;margin:1rem 0;font-weight:600;color:var(--text-main)}.app-input{width:100%;margin-top:.45rem;padding:.7rem;color:var(--text-main);border:1px solid var(--app-border-strong);border-radius:8px;background:var(--app-surface);font:inherit}.app-input:focus{outline:0;border-color:var(--app-primary);box-shadow:var(--shadow-focus)}textarea.app-input{resize:vertical}.check{display:flex;gap:.5rem;align-items:center}.message{color:#166534;margin-top:1rem}.message.error{color:#b91c1c}.tenants-card{margin-top:1rem}.tenant-row{display:flex;justify-content:space-between;align-items:center;padding:.85rem 0;border-top:1px solid var(--app-border)}.tenant-row strong{color:var(--text-main)}.tenant-row small{display:block;margin-top:.2rem}@media(max-width:760px){.cards{grid-template-columns:1fr}}`]
})
export class PlatformWahaSettingsComponent implements OnInit {
  status: WahaStatus | null = null; tenants: Tenant[] = []; selectedTenant: Tenant | null = null; selectedId: number | null = null;
  loading = true; saving = false; message = ''; messageError = false;
  testPhone = ''; testMessage = 'Mensaje de prueba desde MyGym'; testing = false; testResult = ''; testError = false;
  constructor(private tenantService: TenantService) {}
  ngOnInit(): void { this.tenantService.getWahaStatus().subscribe({ next: status => { this.status = status; this.loading = false; }, error: () => this.loading = false }); this.tenantService.getTenants().subscribe({ next: tenants => this.tenants = tenants }); }
  selectTenant(): void { this.selectedTenant = this.tenants.find(t => t.id === this.selectedId) || null; this.message = ''; }
  sendTest(): void { this.testResult = ''; this.testError = false; if (!/^[0-9]{10}$/.test(this.testPhone)) { this.testResult = 'Escribe exactamente 10 dígitos del número mexicano.'; this.testError = true; return; } if (!this.testMessage.trim()) { this.testResult = 'Escribe un mensaje para enviar.'; this.testError = true; return; } this.testing = true; this.tenantService.sendWahaTestMessage(this.testPhone, this.testMessage.trim()).subscribe({ next: result => { this.testResult = `${result.message} (${result.phone})`; this.testing = false; }, error: err => { this.testResult = err?.error?.detail || 'No se pudo enviar el mensaje.'; this.testError = true; this.testing = false; } }); }
  save(): void { if (!this.selectedTenant) return; this.saving = true; this.message = ''; this.tenantService.updateTenant(this.selectedTenant.id, { waha_session: this.selectedTenant.waha_session || '', waha_enabled: !!this.selectedTenant.waha_enabled }).subscribe({ next: tenant => { this.selectedTenant = tenant; this.tenants = this.tenants.map(item => item.id === tenant.id ? tenant : item); this.message = 'Configuración guardada correctamente.'; this.saving = false; }, error: err => { this.message = err?.error?.detail || 'No se pudo guardar la configuración.'; this.messageError = true; this.saving = false; } }); }
}
